# Generated by Django 5.0.1 on 2024-01-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
    ]
