# Generated by Django 5.0.1 on 2024-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_risk',
            field=models.CharField(choices=[('HI', 'High'), ('MI', 'Medium'), ('LO', 'Low')], default='LO', max_length=2),
        ),
    ]
