# Generated by Django 5.0.1 on 2024-02-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_picture_remove_job_images_job_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='job_documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='documents',
        ),
        migrations.AlterField(
            model_name='job',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='job_img', to='core.picture'),
        ),
        migrations.AddField(
            model_name='job',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='job_doc', to='core.document'),
        ),
    ]
