# Generated by Django 5.0.1 on 2024-02-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_job_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='display_image',
            field=models.ImageField(blank=True, default=' job_images/rest_logo.jpg ', null=True, upload_to='job_images/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
