# Generated by Django 5.0.1 on 2024-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_job_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='display_image',
            field=models.ImageField(blank=True, default='job_images/rest_logo.jpg', upload_to='job_images/'),
        ),
    ]
