# Generated by Django 5.0.1 on 2024-02-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_job_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='images',
            field=models.ImageField(blank=True, default='employee_images/human_placeholder.png', null=True, upload_to='employee_images/'),
        ),
    ]
