# Generated by Django 5.0.1 on 2024-02-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_employee_email_alter_employee_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('PN', 'Panel'), ('IN', 'Inverter'), ('BA', 'Battery')], default='PN', max_length=2)),
                ('stock_status', models.CharField(choices=[('NW', 'New'), ('UD', 'Used')], default='NW', max_length=2)),
                ('barcode', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
