# Generated by Django 5.0.1 on 2024-02-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_inventory_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
