# Generated by Django 5.0.3 on 2024-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, default='none', null=True),
        ),
    ]
