# Generated by Django 5.0.3 on 2024-04-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_employee_address_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_progress',
            field=models.CharField(choices=[('CS', 'Consultation'), ('IP', 'In progress'), ('FN', 'Finished'), ('CL', 'Closed')], default='CS', max_length=2),
        ),
    ]
