# Generated by Django 5.0.1 on 2024-06-09 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_job_amount_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='actual_end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
