# Generated by Django 5.0.1 on 2024-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_amount_job_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='maintenane_type',
            field=models.CharField(choices=[('YR', 'Yearly'), ('BA', 'Bi Annual')], default='YR', max_length=2),
        ),
    ]
