# Generated by Django 5.0.1 on 2024-08-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_job_lease_job_maintenane_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='maintenane_type',
            new_name='maintenance_type',
        ),
    ]
