# Generated by Django 5.0.1 on 2024-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_employee_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
