# Generated by Django 5.0.1 on 2024-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_employee_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('CU', 'Current'), ('PE', 'Past Employee')], default='CU', max_length=2),
        ),
    ]
