# Generated by Django 5.0.1 on 2024-10-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_job_lease_job_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_type',
            field=models.CharField(choices=[('DP', 'Direct Purchase'), ('LS', 'Lease')], default='DP', max_length=2),
        ),
    ]
