# Generated by Django 5.0.1 on 2024-10-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(choices=[('NW', 'New'), ('RC', 'Recurrent'), ('RF', 'Referral'), ('TP', 'Third Party')], default='NW', max_length=2),
        ),
    ]
