# Generated by Django 5.0.3 on 2024-04-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_inventory'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='in_use',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='battery',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery_job', to='core.job'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='in_use',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='inverter',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inverter_job', to='core.job'),
        ),
        migrations.AddField(
            model_name='panel',
            name='in_use',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='panel',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel_job', to='core.job'),
        ),
    ]
