# Generated by Django 5.0.3 on 2024-04-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_battery_in_use_battery_job_inverter_in_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='serial',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, unique=True),
        ),
    ]
