# Generated by Django 5.0.3 on 2024-04-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_battery_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='size',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, unique=True),
        ),
    ]
