# Generated by Django 5.0.3 on 2024-04-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_panel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='serial',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, unique=True),
        ),
    ]
