# Generated by Django 5.0.3 on 2024-04-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inverter_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='assigned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
