# Generated by Django 5.0.1 on 2024-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inverter_assigned_panel_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='grid_type',
            field=models.CharField(choices=[('NG', 'On Grid'), ('OG', 'Off Grid'), ('HB', 'Hybrid')], default='NG', max_length=2),
        ),
    ]
