# Generated by Django 5.0.1 on 2024-06-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_alter_job_job_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, default='None', null=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
    ]
