# Generated by Django 5.0.1 on 2024-05-31 08:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_alter_job_job_progress'),
        ('inventory', '0007_inverter_assigned_panel_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BA', 'Battery'), ('IN', 'Inverter'), ('PN', 'Panel')], default='BA', max_length=2)),
                ('model', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('size', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('date_received', models.DateField(blank=True, default=None, null=True)),
                ('order_status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', max_length=2)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_brands', to='inventory.brand')),
                ('job', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='core.job')),
            ],
        ),
    ]
